version: "3"

tasks:
  templ:
    cmds:
      - templ generate --watch --proxy="http://localhost:3000" --cmd="go run ."

  tailwind:
    cmds:
      - npx tailwindcss -i ./pages/global.css -o ./public/styles.css --watch

  run:
    deps: [templ, tailwind]
    cmds:
      - echo "Killing Application..."
