version: "3"

tasks:
  templ:
    cmds:
      - templ generate --proxy="http://localhost:3000" --cmd="go run ." --watch --lazy

  tailwind:
    cmds:
      - npx tailwindcss -i ./pages/main.css -o ./public/styles.css --watch

  run:
    deps: [templ, tailwind]
    cmds:
      - echo "Killing Application..."
