version: "3"

tasks:
  setup:
    cmds:
      - templ generate
      - go mod tidy
      - npx tailwindcss -i ./app/main.css -o ./public/styles.css --minify

  deploy:
    deps: [setup]
    cmds:
      - sam build
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset

  run:
    deps: [tailwind, templ]
    cmds:
      - echo "Killing Application..."

  templ:
    cmds:
      - templ generate --proxy="http://localhost:3000" --cmd="go run ." --watch --lazy

  tailwind:
    cmds:
      - npx tailwindcss -i ./app/main.css -o ./public/styles.css --watch --minify
