version: "3"

tasks:
  setup:
    cmds:
      - bun install
      - templ generate
      - go mod tidy
      - bun tailwindcss -i ./app/main.css -o ./public/css/styles.css --minify
      - bun esbuild "./app/**/*.ts" --outdir=public/js --bundle --minify

  deploy:
    deps: [setup]
    cmds:
      - sam build
      - sam deploy --no-confirm-changeset

  run:
    deps: [templ, tailwind, esbuild]
    cmds:
      - echo "Killing Application..."

  templ:
    cmds:
      - templ generate --proxy="http://localhost:3000" --cmd="go run ." --watch --lazy

  tailwind:
    cmds:
      - bun tailwindcss -i ./app/main.css -o ./public/css/styles.css --watch --minify

  esbuild:
    cmds:
      - bun esbuild "./app/**/*.ts" --outdir=public/js --bundle --watch --minify
