AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Resources:
  server:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: . # folder where your main program resides
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures: [x86_64]
      FunctionUrlConfig:
        AuthType: NONE
