AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Huma

  Sample SAM Template for Huma with CloudFront

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  HumaFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./
      Handler: bootstrap
      Runtime: provided.al2023
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED
      Architectures:
        - x86_64
      Environment:
        Variables:
          PARAM1: VALUE

  HumaCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: HumaLambdaOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        Origins:
          - Id: HumaLambdaOrigin
            DomainName: "v6joheaex5b5m4epjvoyv2xare0iimba.lambda-url.us-east-2.on.aws"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
        DefaultRootObject: ""
        Aliases:
          - "go.xonha.space" # Replace with your domain name
        ViewerCertificate:
          AcmCertificateArn: "arn:aws:acm:us-east-1:536044156294:certificate/362c8ac8-9042-40ea-8b63-e5411d8cf8ce" # Replace with your ACM certificate ARN
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

Outputs:
  HumaFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt HumaFunction.Arn
  HumaFunctionIamRole:
    Description: "Implicit IAM Role created for Huma function"
    Value: !GetAtt HumaFunctionRole.Arn
  HumaFunctionUrlEndpoint:
    Description: "My Lambda Function URL Endpoint"
    Value: !GetAtt HumaFunctionUrl.FunctionUrl
  HumaCloudFrontEndpoint:
    Description: "CloudFront Distribution URL for the Lambda Function URL"
    Value: !Sub "https://${HumaCloudFront.DomainName}"
